parameters:
    scaytrase_utils_sms_delivery.dummy_sender.class: ScayTrase\Utils\SMSDeliveryBundle\Service\DummySender\DummyMessageDeliveryService
    sms_delivery.class: 'ScayTrase\Utils\SMSDeliveryBundle\Service\DummySender\DummyMessageDeliveryService'

services:
    sms_delivery.dummy_sender:
        class: %scaytrase_utils_sms_delivery.dummy_sender.class%
        arguments: [@service_container]

    sms_delivery.sender:
        class: %sms_delivery.class%
        arguments: [@service_container]

    data_collector.sms_delivery.data_collector:
        class: ScayTrase\Utils\SMSDeliveryBundle\DataCollector\MessageDeliveryDataCollector
        arguments: ['@sms_delivery.sender']
        tags:
            - { name: data_collector, template: "SMSDeliveryBundle:DataCollector:data_collector", id: "sms_delivery.data_collector" }