parameters:
    sms_delivery.transport: @sms_delivery.dummy_sender
    sms_delivery.disable_delivery: false
    sms_delivery.delivery_recipient: null

services:
    sms_delivery.dummy_sender:
        class: ScayTrase\SmsDeliveryBundle\Transport\DummyTransport
        arguments: [@service_container]

    sms_delivery.sender:
        class: ScayTrase\SmsDeliveryBundle\Service\MessageDeliveryService
        arguments:
        - %sms_delivery.transport%
        - %sms_delivery.disable_delivery%
        - %sms_delivery.delivery_recipient%

    data_collector.sms_delivery.data_collector:
        class: ScayTrase\SmsDeliveryBundle\DataCollector\MessageDeliveryDataCollector
        arguments: ['@sms_delivery.sender']
        tags:
            - { name: data_collector, template: "SMSDeliveryBundle:DataCollector:data_collector", id: "sms_delivery.data_collector" }
